### ISSUE TITLE
[idea] Predefined tags 

### ISSUE THREAD

**Issue by zeus-web** [davecburke/silverbullet-clipper#12]
Just an Idea for improvement:

Would it be possible to define tags in the config, which are predefined (but editable) for every new note?
I'd like that to tag every clipped note e.g. as "webclip", so I am able to search for them later on.

**Comment by davecburke** [comment]
That's a great idea! I played around with trying to pull tags from SilverBullet so you can select them in the clipper but it was all getting too hard. Your idea is a good compromise. I'll add it to the list. Thanks for the feedback.
