### ISSUE TITLE
Doesn't seem to support SB 0.9.4

### ISSUE THREAD

**Issue by mufeedali** [davecburke/silverbullet-clipper#14]
Note gets created, including title, metadata, etc. But the article content isn't copied over.

Example article: https://selfh.st/newsletter/2024-11-08/
Tried with both Firefox and Brave

SB: 0.9.4
Clipper: 1.2.4

**Comment by dklawren** [comment]
You are correct that it does not copy the entire page over, but if you highlight some text on the page with the mouse and then clip, it will add the highlighted text to the new note.

**Comment by davecburke** [comment]
Thanks for answering @dklawren. This is correct.

**Comment by mufeedali** [comment]
I think it might be good to document this.

The README says:
> To use this add-on, simply click the extension icon while you are browsing the page you want to capture.

So I expected it to behave like other clippers (Obsidian's new clipper extension for example), where the extension attempts to automatically pick up the article content.

**Comment by davecburke** [comment]
Thanks for the feedback Mufeed. I've updated the readme to be more clear.

**Comment by mufeedali** [comment]
Thanks! Loving this btw :)
