### ISSUE TITLE
Sanitize the `source-page-title`'s values containing special YAML characters

### ISSUE THREAD

**Issue by mjf** [davecburke/silverbullet-clipper#15]
Getting `bad indentation of a mapping entry` if the `source-page-title` contains special YAML characters, *e.g.*, if it contains collon character then it's considered a "nested mapping" (`yamllint` returns: "Nested mappings are not allowed in compact mappings at line [...]"). This can be fixed by manualy quoting the string with either single or double quotes etc. Could the `source-page-title` be somehow sanitized in case it contains special YAML characters to avoid such additional manual interventions?

**Comment by davecburke** [comment]
Hi mjf, thanks for bringing this to my attention. I'll look into it over the weekend.

**Comment by davecburke** [comment]
Hi mjf, I've fixed the invalid characters and released v1.2.5. I've opened a new issue with your customisable yaml and file name

**Comment by mjf** [comment]
@davecburke That's great, looking forward to it. Thank you!
