### ISSUE TITLE
Problems with Page title

### ISSUE THREAD

**Issue by zeus-web** [davecburke/silverbullet-clipper#8]
I have a strange problem with the predefined title, which the clipper applet suggests:

If I leave the suggested e.g. "2024-09-06 18:52:11" it leads to an error, I see in the console log, that silverbullet/JS is not able to write to the file.
This does not happen, if I change the title to e.g. "Test" or even "2024-09-06 1852"
As I'm running it on a windows machine, I suggest, it has some problems with the ":" in the name. 

So my wish is to have some other options for the suggested values...

Thanks a lot!

**Comment by davecburke** [comment]
What browser are you using?

**Comment by davecburke** [comment]
SilverBullet now uses dashes as the separator for time instead of colons. I've updated SilverBullet Clipper (v1.2.1) to do the same. Hopefully this will fix your issue.
